export const FETCH_HOME_MULTIDATA = "FETCH_HOME_MULTIDATA";

export const ALBUM_FETCH_REQUESTED = "ALBUM_FETCH_REQUESTED";
export const ALBUM_FETCH_SUCCEEDED = "ALBUM_FETCH_SUCCEEDED";
export const ALBUM_FETCH_FAILED = "ALBUM_FETCH_FAILED";

export const CHANGE_BANNERS = "CHANGE_BANNERS";
export const CHANGE_RECOMMEND = "CHANGE_RECOMMEND";